### ISSUE TITLE
To add Mega Menu html code in Menu

### ISSUE THREAD

**Issue by ainurwazir** [lipemat/advanced-sidebar-menu#2]
Before this under Appearance> Menu, there is an option for Show Menu Option, from there I can add mega menu html code. Now, I noticed that function missing.  How can enable it back
![previous option in menu](https://user-images.githubusercontent.com/34537437/33983975-fdc5c7dc-e0f0-11e7-82b1-adf1cf96264f.GIF)

**Comment by lipemat** [comment]
I'm afraid the functionality you speak of is not part of this plugin.
